### ISSUE TITLE
Is iOS supported?

### ISSUE THREAD

**Issue by K1N5L4Y3R** [hypertrack/hypertrack-cordova#5]
When calling plugin's functions (e.g. `getOrCreateUser()` or `setUserId()`) **in iOS**, I get no response. I inspected src/ios/HyperTrackWrapper.swift and see no implementation for any functions other than `helloWorld()`. Does this mean that iOS is still not implemented? If so, when can we expect an iOS implementation?

**Comment by arjun27** [comment]
iOS is in the roadmap. Do you have some specific APIs that you want to be supported first? Will help us prioritise

**Comment by K1N5L4Y3R** [comment]
The first methods that I would use would be

```
getOrCreateUser
startTracking
stopTracking
```

After that, the calls that have to do with `Actions`.

I have subscribed to releases of this plugin, so I guess I can close this issue for now, and I can wait for gradual iOS support. Thanks!
