### ISSUE TITLE
Environment setting

### ISSUE THREAD

**Issue by K1N5L4Y3R** [hypertrack/hypertrack-cordova#6]
I can see in the Hypertrack dashboard that there are 2 environments (Production and Test). After playing with the plugin, I created a user and I can see that it was created for the Production environment by default. Just checking if there's a way to setting the environment with this plugin.

**Comment by arjun27** [comment]
@K1N5L4Y3R - the two environments have different publishable keys. The production key looks like `pk_abc123` and the test key looks like `pk_test_abc123`. You can change the configured token to change the environment.

**Comment by K1N5L4Y3R** [comment]
I see. Didn't notice those changed when changing environments in the dashboard. Thanks!
