### ISSUE TITLE
Notification text

### ISSUE THREAD

**Issue by K1N5L4Y3R** [hypertrack/hypertrack-cordova#7]
Is there a way to change the local notification text in Android?

"[APP NAME] is running. Touch here to open the app"

**Comment by arjun27** [comment]
Yes, you can change the local notification text with some native code. Docs link: https://docs.hypertrack.com/sdks/android/notification.html

**Comment by K1N5L4Y3R** [comment]
Thanks for the info. Any plans on making the strings accessible to the Cordova app itself (e.g. a preference in the app's config.xml, or programatically)?

**Comment by arjun27** [comment]
We could add some limited customisation in the wrapper. Are you only
looking to change the text?

**Comment by K1N5L4Y3R** [comment]
I'd like to change `ht_service_notification_title` and `ht_service_notification_text` mainly. If possible, the icons would also be nice, but that's certainly not urgently needed. I appreciate your support in all of my issues.
